### PR TITLE
fix: not to remove node_modules

### LINKED ISSUE #195: learn.svelte.dev crashing
I was happily doing tutors on learn.svelte.dev util I go to https://learn.svelte.dev/tutorial/select-bindings and this error pop up:

Error [ENOENT]: ENOENT: no such file or directory, open '/home/learnsveltedev-uthj/node_modules/@sveltejs/kit/src/core/config/default-error.html'

Screenshot 2023-01-26 at 1 31 39 AM

### PR DESCRIPTION
**Pull request by tomoam**
fix #195 

This is due to `node_modules` being removed when switching tutorials. This only happens when switching from one tutorial with its own `node_modules` to another.

https://github.com/sveltejs/learn.svelte.dev/blob/7f6d1d31486902000965fcdcca9065c38fb9af7b/src/lib/client/adapters/webcontainer/index.js#L141

https://github.com/sveltejs/learn.svelte.dev/blob/7f6d1d31486902000965fcdcca9065c38fb9af7b/src/lib/client/adapters/webcontainer/index.js#L170-L172

This PR is only an ad-hoc fix, but I submit it because I suppose it would be better than the tutorial not working.

### CODE REVIEW

File: src/lib/client/adapters/webcontainer/index.js [hunk 1]
```diff
@@ -138,6 +138,9 @@ export async function create(stubs, callback) {
 				current_stubs.delete(stub.name);
 			}
 
+			const common_hidden_stubs = ['/node_modules', '/node_modules/.bin'];
+			common_hidden_stubs.forEach((name) => current_stubs.delete(name));
```
Comment (dummdidumm) [inline src/lib/client/adapters/webcontainer/index.js:142]:
```suggestion
			// Hack: don't delete the node_modules folder when switching from one exercise to another
			// where it's no longer needed, as this crashes the dev server.
			['/node_modules', '/node_modules/.bin'].forEach((name) => current_stubs.delete(name));
```

**Review by dummdidumm — APPROVED** [review]
Thank you!
