### PR TITLE
fix: add scripts to each package.json

### LINKED ISSUE #178: Part 1 / Lifecycle / beforeUpdate and afterUpdate: "runScript Failed to run `dev`. Script is missing."
https://learn.svelte.dev/tutorial/update

The preview does not load and the console errors:
"index-dbfff98c.js:1 [dev] ERR!: runScript Failed to run `dev`. Script is missing."

### PR DESCRIPTION
**Pull request by tomoam**
fix #178 

This is because the `dev` script is not present in each package.json when running `turbo run dev` in the background.
https://github.com/sveltejs/learn.svelte.dev/blob/7f6d1d31486902000965fcdcca9065c38fb9af7b/src/lib/client/adapters/webcontainer/index.js#L86

The same issue also occurs at https://learn.svelte.dev/tutorial/textarea-inputs, but there is another issue here.

image

This PR fixes both issues.

### CODE REVIEW

File: scripts/create-common-bundle/unzip.js [hunk 1]
```diff
@@ -4,7 +4,7 @@ import AdmZip from 'adm-zip';
 const zip = new AdmZip('common.zip');
 zip.extractAllTo('.');
 
-fs.mkdirSync('node_modules/.bin');
+fs.existsSync('node_modules/.bin') || fs.mkdirSync('node_modules/.bin');
```
Comment (dummdidumm) [inline scripts/create-common-bundle/unzip.js:7]:
```suggestion
if (!fs.existsSync('node_modules/.bin')) {
	fs.mkdirSync('node_modules/.bin');
}
```

**Review by dummdidumm — APPROVED** [review]
Thank you for fixing all these annoying bugs - really appreciated!
